const register = require('./controlls/users/register.js')
const authenticate = require('./controlls/users/authenticate')
const DisplayUserData = require('./controlls/users/DisplayUserData.js')
const CookieVerification = require('./controlls/users/AuthenticationCheck/CookieVerification.js')
const logout = require('./controlls/users/logout.js')
const DeleteAccount = require('./controlls/users/delete.js')
const update = require('./controlls/users/update.js')
const addfood = require('./controlls/foods/register.js')
const usersfoods = require('./controlls/foods/UsersFood.js')
const ShowAllFoodForName = require ('./controlls/foods/ShowAllFood.js')
const editfoods = require('./controlls/foods/editFood.js')
const Breakfast = require('./controlls/foods/DailyCalories/Breakfast.js')
const Dinner = require('./controlls/foods/DailyCalories/Dinner.js')
const Lunch = require('./controlls/foods/DailyCalories/Lunch.js')
const TotalDailyCalories = require('./controlls/foods/DailyCalories/TotalDailyCalories.js')
const express = require('express')
const router = express.Router()

router.post('/authenticate',authenticate.authenticateUser)
router.post('/register',register.registerUser)
router.get('/account',CookieVerification.verifyJWT, DisplayUserData.ShowData)
router.get('/logout',CookieVerification.verifyJWT, logout.quit)
router.delete('/delete/account',CookieVerification.verifyJWT, DeleteAccount.delete)
router.put('/account/update',CookieVerification.verifyJWT, update.UpdateUserData)
router.post('/foods/add',CookieVerification.verifyJWT, addfood.RegisterFood)
router.get('/foods/show',CookieVerification.verifyJWT, usersfoods.showFoods)
router.post('/foods/find',CookieVerification.verifyJWT, ShowAllFoodForName.showFoods)
router.post('/foods/edit',CookieVerification.verifyJWT, editfoods.UpdateFoodData)
router.post('/foods/add/breakfast', CookieVerification.verifyJWT, Breakfast.addfood)
router.post('/foods/add/dinner', CookieVerification.verifyJWT, Dinner.addfood)
router.post('/foods/add/lunch', CookieVerification.verifyJWT, Lunch.addfood)
router.get('/foods/TotalDailyCalories', CookieVerification.verifyJWT, TotalDailyCalories.TotalKcal)
module.exports = router